import { SceneConfig } from '../types/profile';

export const SCENES: SceneConfig[] = [
  {
    id: 'mentor',
    label: '导师简介页 Mentor',
    defaultTheme: 'academic_blue',
    supportedSizes: ['a4', 'long', 'custom'],
    templates: [
      { id: 'luxury_editorial', label: '奢华画报 Luxury Editorial' },
      { id: 'editorial_big_title', label: '大标题杂志风 Editorial' },
      { id: 'minimal_swiss', label: '瑞士极简 Minimal Swiss' },
      { id: 'playful_designer', label: '设计师趣玩 Playful' },
      { id: 'playful_editorial_grid', label: '趣玩网格 Playful Grid' },
    ],
    schema: [
      { id: 'avatar', label: '头像 Avatar', type: 'image' },
      { id: 'name', label: { zh: '姓名', en: 'Name' }, type: 'text', placeholder: '请输入姓名', bilingual: true },
      { id: 'title', label: { zh: '头衔', en: 'Title' }, type: 'text', placeholder: '如：资深留学顾问', bilingual: true },
      { id: 'education', label: { zh: '教育背景', en: 'Education' }, type: 'textarea', placeholder: '每行一个教育经历', bilingual: true },
      { id: 'teachingAreas', label: { zh: '教学领域', en: 'Teaching Areas' }, type: 'taglist', placeholder: '输入标签，用逗号或回车分隔', bilingual: true },
      { id: 'offerCases', label: { zh: '录取案例', en: 'Offer Cases' }, type: 'list', placeholder: '每行一个案例', bilingual: true },
      { id: 'advantages', label: { zh: '核心优势', en: 'Advantages' }, type: 'textarea', bilingual: true },
      { id: 'theories', label: { zh: '教学理念', en: 'Theories' }, type: 'textarea', bilingual: true },
      { id: 'skills', label: { zh: '专业技能', en: 'Skills' }, type: 'taglist', bilingual: true },
      { id: 'projects', label: { zh: '项目展示', en: 'Projects' }, type: 'gallery' },
    ],
  },
  {
    id: 'student',
    label: '学员简介页 Student',
    defaultTheme: 'warm_beige',
    supportedSizes: ['a4', 'long', 'custom'],
    templates: [
      { id: 'luxury_editorial', label: '奢华画报 Luxury Editorial' },
      { id: 'editorial_big_title', label: '大标题杂志风 Editorial' },
      { id: 'playful_designer', label: '设计师趣玩 Playful' },
      { id: 'minimal_swiss', label: '瑞士极简 Minimal Swiss' },
    ],
    schema: [
      { id: 'avatar', label: '头像 Avatar', type: 'image' },
      { id: 'name', label: { zh: '姓名', en: 'Name' }, type: 'text', bilingual: true },
      { id: 'school', label: { zh: '就读学校', en: 'School' }, type: 'text', bilingual: true },
      { id: 'major', label: { zh: '专业', en: 'Major' }, type: 'text', bilingual: true },
      { id: 'gpa', label: 'GPA', type: 'text' },
      { id: 'languageScores', label: { zh: '语言成绩', en: 'Language Scores' }, type: 'taglist' },
      { id: 'portfolioProjects', label: { zh: '作品集项目', en: 'Portfolio Projects' }, type: 'gallery' },
      { id: 'offerResults', label: { zh: '录取结果', en: 'Offer Results' }, type: 'list', bilingual: true },
      { id: 'personalStatement', label: { zh: '个人陈述', en: 'Personal Statement' }, type: 'textarea', bilingual: true },
      { id: 'targetPrograms', label: { zh: '目标项目', en: 'Target Programs' }, type: 'taglist', bilingual: true },
    ],
  },
  {
    id: 'phd',
    label: '博士申请简介页 PhD',
    defaultTheme: 'black_white',
    supportedSizes: ['a4', 'long', 'custom'],
    templates: [
      { id: 'luxury_editorial', label: '奢华画报 Luxury Editorial' },
      { id: 'minimal_swiss', label: '瑞士极简 Minimal Swiss' },
      { id: 'editorial_big_title', label: '大标题杂志风 Editorial' },
      { id: 'playful_designer', label: '设计师趣玩 Playful' },
    ],
    schema: [
      { id: 'avatar', label: '头像 Avatar', type: 'image' },
      { id: 'name', label: { zh: '姓名', en: 'Name' }, type: 'text', bilingual: true },
      { id: 'currentInstitution', label: { zh: '当前机构', en: 'Current Institution' }, type: 'text', bilingual: true },
      { id: 'researchInterests', label: { zh: '研究兴趣', en: 'Research Interests' }, type: 'taglist', bilingual: true },
      { id: 'publications', label: { zh: '发表论文', en: 'Publications' }, type: 'list', bilingual: true },
      { id: 'proposalSummary', label: { zh: '研究计划摘要', en: 'Proposal Summary' }, type: 'textarea', bilingual: true },
      { id: 'methodology', label: { zh: '研究方法', en: 'Methodology' }, type: 'textarea', bilingual: true },
      { id: 'supervisorMatch', label: { zh: '导师匹配度', en: 'Supervisor Match' }, type: 'textarea', bilingual: true },
      { id: 'awards', label: { zh: '获奖经历', en: 'Awards' }, type: 'list', bilingual: true },
    ],
  },
];
