import { ThemeType, ThemeTokens } from '../types/profile';

export const THEMES: Record<ThemeType, ThemeTokens> = {
  black_white: {
    label: 'Noir & Blanc',
    primary: '#1A1A1A',
    secondary: '#F5F5F5',
    background: '#FDFDFD',
    text: '#262626',
    muted: '#8C8C8C',
    border: '#E8E8E8',
    accent: '#1A1A1A',
    gradient: 'linear-gradient(135deg, #F9F9F9 0%, #FFFFFF 100%)',
    fontSans: 'Inter',
    fontSerif: 'Playfair Display',
    fontDisplay: 'Outfit',
  },
  academic_blue: {
    label: 'Oxford Blue',
    primary: '#1E293B',
    secondary: '#F8FAFC',
    background: '#FDFDFD',
    text: '#334155',
    muted: '#94A3B8',
    border: '#F1F5F9',
    accent: '#3B82F6',
    gradient: 'radial-gradient(circle at top left, #F8FAFC, #FFFFFF)',
    fontSans: 'Inter',
    fontSerif: 'Playfair Display',
    fontDisplay: 'Outfit',
  },
  warm_beige: {
    label: 'Desert Sand',
    primary: '#451A03',
    secondary: '#FFFBEB',
    background: '#FDF8F1',
    text: '#78350F',
    muted: '#B45309',
    border: '#FEF3C7',
    accent: '#D97706',
    gradient: 'linear-gradient(to bottom right, #FFFBEB, #FEF3C7)',
    fontSans: 'Inter',
    fontSerif: 'Playfair Display',
    fontDisplay: 'Outfit',
  },
  dark_portfolio: {
    label: 'Midnight',
    primary: '#F5F5F5',
    secondary: '#1A1A1A',
    background: '#0F0F0F',
    text: '#D4D4D4',
    muted: '#737373',
    border: '#262626',
    accent: '#F5F5F5',
    gradient: 'radial-gradient(circle at center, #171717 0%, #0A0A0A 100%)',
    fontSans: 'Inter',
    fontSerif: 'Playfair Display',
    fontDisplay: 'Outfit',
  },
  luxury_gold: {
    label: 'Luxury Gold',
    primary: '#B59458',
    secondary: '#FDFBF7',
    background: '#FDFDFD',
    text: '#262626',
    muted: '#A3A3A3',
    border: '#F5F1E8',
    accent: '#B59458',
    gradient: 'linear-gradient(135deg, #FFFFFF 0%, #FDFBF7 100%)',
    fontSans: 'Inter',
    fontSerif: 'Playfair Display',
    fontDisplay: 'Outfit',
  },
  red_accent: {
    label: 'Red Accent',
    primary: '#1A1A1A',
    secondary: '#F9FAFB',
    background: '#FFFFFF',
    text: '#262626',
    muted: '#737373',
    border: '#E5E7EB',
    accent: '#D94A4A',
    gradient: 'linear-gradient(135deg, #F9FAFB 0%, #FFFFFF 100%)',
    fontSans: 'Inter',
    fontSerif: 'Playfair Display',
    fontDisplay: 'Outfit',
  },
};
